export const ppksPrintData = {
  Jenis_PPKS: [
    'ODKB', 'ADK', 'AY_AP_AYP', 'AT', 'ABH', 'AJ', 'ABT', 'AKTK', 'PRSE', 'KTK', 
    'LUT', 'PD', 'TS', 'PGMS', 'GLDG', 'BWBLK', 'NAPZA', 'FM', 'RTLH', 'KR', 
    'KBSP', 'KAT', 'KBA', 'KBS', 'PM', 'ODHA'
  ],
  Kabupaten: [
    'Aceh Barat', 'Aceh Barat Daya', 'Aceh Besar', 'Aceh Jaya', 'Aceh Selatan', 
    'Aceh Singkil', 'Aceh Tamiang', 'Aceh Tengah', 'Aceh Tenggara', 'Aceh Timur', 
    'Aceh Utara', 'Bener Meriah', 'Bireuen', 'Gayo Lues', 'Kota Banda Aceh', 
    'Kota Langsa', 'Kota Lhokseumawe', 'Kota Sabang', 'Kota Subulussalam', 
    'Nagan Raya', 'Pidie', 'Pidie Jaya', 'Simeulue'
  ],
  Kecamatan: [
    'Longkib', 'Penanggalan', 'Rundeng', 'Simpang Kiri', 'Sultan Daulat', 
    'Kecamatan X', 'Kecamatan Y', 'Kecamatan Z'
  ],
  Desa: [
    'Desa A', 'Desa B', 'Desa C', 'Desa D', 'Desa E', 
    'Desa F', 'Desa G', 'Desa H'
  ],
  ExamplePPKSData: [
    {
      Jenis_PPKS: 'ODKB',
      Kabupaten: 'Aceh Barat',
      Kecamatan: 'Longkib',
      Gampong: 'Desa A',
      Nama: 'John Doe',
      NIK: '1234567890123456',
      JK: 'L',
      Tanggal_Lahir: '2000-01-01',
      Alamat: 'Jl. Contoh No. 1, Aceh Barat',
      Pernah_Mendapat_Bantuan: 'Ya',
      Jenis_Bantuan: 'Bantuan Sosial'
    },
    {
      Jenis_PPKS: 'ADK',
      Kabupaten: 'Aceh Selatan',
      Kecamatan: 'Penanggalan',
      Gampong: 'Desa B',
      Nama: 'Jane Smith',
      NIK: '6543210987654321',
      JK: 'P',
      Tanggal_Lahir: '1995-05-05',
      Jenis_Kecacatan: 'Cacat Fisik',
      Status_Anak: 'Aktif',
      Pendidikan: 'S1',
      Ayah: 'Budi Smith',
      Pekerjaan_Ayah: 'Petani',
      Ibu: 'Siti Smith',
      Pekerjaan_Ibu: 'Ibu Rumah Tangga',
      Wali: 'Kakek',
      Pekerjaan_Wali: 'Pensiunan',
      Alamat: 'Jl. Contoh No. 2, Aceh Selatan',
      Pernah_Mendapat_Bantuan: 'Tidak',
      Jenis_Bantuan: 'N/A'
    },
    {
      Jenis_PPKS: 'AY_AP_AYP',
      Kabupaten: 'Aceh Besar',
      Kecamatan: 'Sultan Daulat',
      Gampong: 'Desa C',
      Nama: 'Ali Ahmad',
      NIK: '9876543210123456',
      JK: 'L',
      Tanggal_Lahir: '1988-10-10',
      Status_Anak: 'Yatim',
      Pendidikan: 'D3',
      Ayah: 'Slamet',
      Pekerjaan_Ayah: 'Almarhum',
      Ibu: 'Fatma',
      Pekerjaan_Ibu: 'Ibu Rumah Tangga',
      Wali: 'Nenek',
      Pekerjaan_Wali: 'Pensiunan',
      Alamat: 'Jl. Contoh No. 3, Aceh Besar',
      Pernah_Mendapat_Bantuan: 'Ya',
      Jenis_Bantuan: 'Bantuan Kesehatan'
    },
    {
      Jenis_PPKS: 'AT',
      Kabupaten: 'Bener Meriah',
      Kecamatan: 'Rundeng',
      Gampong: 'Desa D',
      Nama: 'Siti Fatimah',
      NIK: '4567891234567890',
      JK: 'P',
      Tanggal_Lahir: '1990-12-12',
      Pendidikan: 'SD',
      Alamat: 'Jl. Contoh No. 4, Bener Meriah',
      Pernah_Mendapat_Bantuan: 'Ya',
      Jenis_Bantuan: 'Bantuan Pendidikan'
    },
    {
      Jenis_PPKS: 'ABH',
      Kabupaten: 'Aceh Tamiang',
      Kecamatan: 'Simpang Kiri',
      Gampong: 'Desa E',
      Nama: 'Muhammad Ibrahim',
      NIK: '7894561231234567',
      JK: 'L',
      Tanggal_Lahir: '1998-07-07',
      Pendidikan: 'SMP',
      Alamat: 'Jl. Contoh No. 5, Aceh Tamiang',
      Status_ABH: 'Delik Ringan',
      Jenis_Kasus: 'Kasus Pencurian',
      Tanggal_Masuk: '2024-01-01',
      Tanggal_Keluar: '2024-01-15',
      Pernah_Mendapat_Bimbingan: 'Ya',
      Pernah_Mendapat_Pendamping_Hukum: 'Tidak',
      Pernah_Mendapat_Bantuan: 'Ya',
      Jenis_Bantuan: 'Bantuan Sosial'
    },
    {
      Jenis_PPKS: 'AJ',
      Kabupaten: 'Aceh Tengah',
      Kecamatan: 'Kecamatan X',
      Gampong: 'Desa F',
      Nama: 'Fatima Zahra',
      NIK: '3216549876543210',
      JK: 'P',
      Tanggal_Lahir: '1985-03-25',
      Pendidikan: 'SMA',
      Alamat: 'Jl. Contoh No. 6, Aceh Tengah',
      Pernah_Mendapat_Bimbingan: 'Ya',
      Pernah_Mendapat_Bantuan: 'Bantuan Usaha',
      Jenis_Bantuan: 'Bantuan Usaha'
    },
    {
      Jenis_PPKS: 'ABT',
      Kabupaten: 'Aceh Tenggara',
      Kecamatan: 'Kecamatan Y',
      Gampong: 'Desa G',
      Nama: 'Ahmad Fauzi',
      NIK: '1597532584567890',
      JK: 'L',
      Tanggal_Lahir: '1992-08-08',
      Lokasi_Penemuan: 'Jl. Penemuan No. 1, Aceh Tenggara',
      Yang_Menemukan: 'Warga Setempat',
      Pengasuh_Sementara: 'Kakak',
    },
    {
      Jenis_PPKS: 'NAPZA',
      Kabupaten: 'Aceh Timur',
      Kecamatan: 'Kecamatan Z',
      Gampong: 'Desa H',
      Nama: 'Zahra Putri',
      NIK: '7539514567891230',
      JK: 'P',
      Tanggal_Lahir: '2001-09-09',
      Pendidikan: 'D3',
      Ayah: 'Sudirman',
      Pekerjaan_Ayah: 'Petani',
      Ibu: 'Rina',
      Pekerjaan_Ibu: 'Pedagang',
      Wali: 'Kakek',
      Pekerjaan_Wali: 'Pensiunan',
      Alamat: 'Jl. Contoh No. 8, Aceh Timur',
      Pernah_Mendapat_Bimbingan: 'Ya',
      Pernah_Mendapat_Bantuan: 'Ya',
      Jenis_Bantuan: 'Bantuan Rehabilitasi'
    },
    {
      Jenis_PPKS: 'ODHA',
      Kabupaten: 'Aceh Utara',
      Kecamatan: 'Longkib',
      Gampong: 'Desa A',
      Nama: 'Ridwan Saidi',
      NIK: '9876543210987654',
      JK: 'L',
      Tanggal_Lahir: '1980-04-14',
      Pendidikan: 'SMP',
      Alamat: 'Jl. Contoh No. 9, Aceh Utara',
      Pernah_Mendapat_Perawatan_Medis: 'Ya',
      Pernah_Mendapat_Bantuan: 'Bantuan Kesehatan'
    }
  ]
};
