export const ppksData = [
    { no: 1, nama: "ODKB", kepanjangan: "Orang Dengan Kecacatan Berat" },
    { no: 2, nama: "ADK", kepanjangan: "Anak Dengan Kecacatan" },
    { no: 3, nama: "AY_AP_AYP", kepanjangan: "Anak Yatim, Anak Piatu, Anak Yatim Piatu" },
    { no: 4, nama: "AT", kepanjangan: "Anak Terlantar" },
    { no: 5, nama: "ABH", kepanjangan: "Anak Berhadapan Dengan Hukum" },
    { no: 6, nama: "AJ", kepanjangan: "Anak Jalanan" },
    { no: 7, nama: "ABT", kepanjangan: "Anak Balita Terlantar" },
    { no: 8, nama: "AKTK", kepanjangan: "Anak Korban Tindak Kekerasan" },
    { no: 9, nama: "PRSE", kepanjangan: "Perempuan Rawan Sosial Ekonomi" },
    { no: 10, nama: "KTK", kepanjangan: "Korban Tindak Kekerasan" },
    { no: 11, nama: "LUT", kepanjangan: "Lanjut Usia Terlantar" },
    { no: 12, nama: "PD", kepanjangan: "Penyandang Disabilitas" },
    { no: 13, nama: "TS", kepanjangan: "Tuna Susila" },
    { no: 14, nama: "PGMS", kepanjangan: "Pengemis" },
    { no: 15, nama: "GLDG", kepanjangan: "Gelandangan" },
    { no: 16, nama: "BWBLK", kepanjangan: "Bekas Warga Binaan Lembaga Kemasyarakatan" },
    { no: 17, nama: "NAPZA", kepanjangan: "Korban Penyalahgunaan NAPZA" },
    { no: 18, nama: "FM", kepanjangan: "Fakir Miskin" },
    { no: 19, nama: "RTLH", kepanjangan: "Keluarga Berumah Tidak Layak Huni" },
    { no: 20, nama: "KR", kepanjangan: "Keluarga Rentan" },
    { no: 21, nama: "KBSP", kepanjangan: "Keluarga Bermasalah Sosial Psikologis" },
    { no: 22, nama: "KAT", kepanjangan: "Komunitas Adat Terpencil" },
    { no: 23, nama: "KBA", kepanjangan: "Korban Bencana Alam" },
    { no: 24, nama: "KBS", kepanjangan: "Korban Bencana Sosial atau Pengungsi" },
    { no: 25, nama: "PM", kepanjangan: "Pekerja Migran Bermasalah Sosial" },
    { no: 26, nama: "ODHA", kepanjangan: "Orang Dengan HIV/AIDS" },
];
