export const psksPrintData = {
  Jenis_PSKS: [
    'PSP', 'PSM', 'TAGANA', 'LKS', 'LKSA', 'KT', 'LK3', 'K.PIONER', 'WKSBM', 'WPKS', 'PS', 'D.USAHA', 'TKSK'
  ],
  Kabupaten: [
    'Aceh Barat', 'Aceh Barat Daya', 'Aceh Besar', 'Aceh Jaya', 'Aceh Selatan', 
    'Aceh Singkil', 'Aceh Tamiang', 'Aceh Tengah', 'Aceh Tenggara', 'Aceh Timur', 
    'Aceh Utara', 'Bener Meriah', 'Bireuen', 'Gayo Lues', 'Kota Banda Aceh', 
    'Kota Langsa', 'Kota Lhokseumawe', 'Kota Sabang', 'Kota Subulussalam', 
    'Nagan Raya', 'Pidie', 'Pidie Jaya', 'Simeulue'
  ],
  Kecamatan: [
    'Longkib', 'Penanggalan', 'Rundeng', 'Simpang Kiri', 'Sultan Daulat', 
    'Kecamatan X', 'Kecamatan Y', 'Kecamatan Z'
  ],
  Gampong: [
    'Desa A', 'Desa B', 'Desa C', 'Desa D', 'Desa E', 
    'Desa F', 'Desa G', 'Desa H'
  ],
  ExamplePSKSData: [
    {
      Jenis_PSKS: 'PSP',
      Kabupaten: 'Aceh Barat',
      Kecamatan: 'Longkib',
      Gampong: 'Desa A',
      Nama: 'Andi Pratama',
      NIK: '1234567890123456',
      JK: 'L',
      Tanggal_Lahir: '1985-05-15',
      Pendidikan: 'S1 Kesejahteraan Sosial',
      Pekerjaan: 'Pekerja Sosial Profesional',
      Alamat: 'Jl. Merdeka No. 10, Desa A, Longkib, Aceh Barat'
    },
    {
      Jenis_PSKS: 'PSM',
      Kabupaten: 'Aceh Selatan',
      Kecamatan: 'Penanggalan',
      Gampong: 'Desa B',
      Nama: 'Siti Rahma',
      NIK: '2345678901234567',
      JK: 'P',
      Tanggal_Lahir: '1990-08-20',
      Pendidikan: 'D3 Pekerjaan Sosial',
      Pekerjaan: 'Pekerja Sosial Masyarakat',
      Alamat: 'Jl. Dahlia No. 5, Desa B, Penanggalan, Aceh Selatan'
    },
    {
      Jenis_PSKS: 'TAGANA',
      Kabupaten: 'Aceh Besar',
      Kecamatan: 'Sultan Daulat',
      Gampong: 'Desa C',
      Nama: 'Rudi Hartono',
      NIK: '3456789012345678',
      JK: 'L',
      Tanggal_Lahir: '1988-11-30',
      Pendidikan: 'SMA',
      Pekerjaan: 'Anggota TAGANA',
      Alamat: 'Jl. Melati No. 15, Desa C, Sultan Daulat, Aceh Besar'
    },
    {
      Jenis_PSKS: 'LKS',
      Kabupaten: 'Bener Meriah',
      Kecamatan: 'Rundeng',
      Gampong: 'Desa D',
      Nama_Lembaga: 'Yayasan Peduli Sesama',
      Jumlah_Klien_Laki_Laki: 25,
      Jumlah_Klien_Perempuan: 30,
      Alamat: 'Jl. Kenanga No. 8, Desa D, Rundeng, Bener Meriah',
      Nama: 'Abdul Hamid',
      NIK: '4567890123456789',
      JK: 'L',
      Tanggal_Lahir: '1975-03-10',
      Pendidikan: 'S2 Manajemen',
      Pekerjaan: 'Ketua LKS'
    },
    {
      Jenis_PSKS: 'LKSA',
      Kabupaten: 'Aceh Tamiang',
      Kecamatan: 'Simpang Kiri',
      Gampong: 'Desa E',
      Nama_Lembaga: 'Panti Asuhan Budi Luhur',
      Jumlah_Klien_Laki_Laki: 20,
      Jumlah_Klien_Perempuan: 25,
      Alamat: 'Jl. Anggrek No. 12, Desa E, Simpang Kiri, Aceh Tamiang',
      Nama: 'Sari Indah',
      NIK: '5678901234567890',
      JK: 'P',
      Tanggal_Lahir: '1980-07-22',
      Pendidikan: 'S1 Psikologi',
      Pekerjaan: 'Kepala LKSA'
    },
    {
      Jenis_PSKS: 'KT',
      Kabupaten: 'Aceh Tengah',
      Kecamatan: 'Kecamatan X',
      Gampong: 'Desa F',
      Nama_Lembaga: 'Karang Taruna Muda Berkarya',
      Jumlah_Anggota_Laki_Laki: 30,
      Jumlah_Anggota_Perempuan: 25,
      Alamat: 'Jl. Mawar No. 3, Desa F, Kecamatan X, Aceh Tengah',
      Nama: 'Firmansyah',
      NIK: '6789012345678901',
      JK: 'L',
      Tanggal_Lahir: '1995-09-05',
      Pendidikan: 'S1 Sosiologi',
      Pekerjaan: 'Ketua Karang Taruna'
    },
    {
      Jenis_PSKS: 'LK3',
      Kabupaten: 'Aceh Tenggara',
      Kecamatan: 'Kecamatan Y',
      Gampong: 'Desa G',
      Nama_Lembaga: 'LK3 Harmoni Keluarga',
      Jumlah_Pengurus_Laki_Laki: 5,
      Jumlah_Pengurus_Perempuan: 7,
      Alamat: 'Jl. Cempaka No. 7, Desa G, Kecamatan Y, Aceh Tenggara',
      Nama: 'Nuraini',
      NIK: '7890123456789012',
      JK: 'P',
      Tanggal_Lahir: '1982-12-15',
      Pendidikan: 'S2 Psikologi Keluarga',
      Pekerjaan: 'Ketua LK3'
    },
    {
      Jenis_PSKS: 'K.PIONER',
      Kabupaten: 'Aceh Timur',
      Kecamatan: 'Kecamatan Z',
      Gampong: 'Desa H',
      Nama: 'Agus Setiawan',
      NIK: '8901234567890123',
      JK: 'L',
      Tanggal_Lahir: '1978-06-18',
      Pendidikan: 'S1 Pertanian',
      Pekerjaan: 'Petani Inovator',
      Alamat: 'Jl. Teratai No. 9, Desa H, Kecamatan Z, Aceh Timur'
    },
    {
      Jenis_PSKS: 'WKSBM',
      Kabupaten: 'Aceh Utara',
      Kecamatan: 'Longkib',
      Gampong: 'Desa A',
      Nama_Lembaga: 'WKSBM Sejahtera Bersama',
      Jumlah_Anggota_Laki_Laki: 15,
      Jumlah_Anggota_Perempuan: 20,
      Alamat: 'Jl. Flamboyan No. 11, Desa A, Longkib, Aceh Utara',
      Nama: 'Dewi Safitri',
      NIK: '9012345678901234',
      JK: 'P',
      Tanggal_Lahir: '1987-02-28',
      Pendidikan: 'S1 Ekonomi',
      Pekerjaan: 'Koordinator WKSBM'
    },
    {
      Jenis_PSKS: 'WPKS',
      Kabupaten: 'Bireuen',
      Kecamatan: 'Penanggalan',
      Gampong: 'Desa B',
      Nama: 'Ratna Sari',
      NIK: '0123456789012345',
      JK: 'P',
      Tanggal_Lahir: '1983-10-08',
      Pendidikan: 'S2 Kesejahteraan Sosial',
      Pekerjaan: 'Kepala Dinas Sosial Kabupaten',
      Alamat: 'Jl. Bougenville No. 6, Desa B, Penanggalan, Bireuen'
    },
    {
      Jenis_PSKS: 'PS',
      Kabupaten: 'Gayo Lues',
      Kecamatan: 'Rundeng',
      Gampong: 'Desa C',
      Nama: 'Gunawan Prasetyo',
      NIK: '1234567890123457',
      JK: 'L',
      Tanggal_Lahir: '1992-04-25',
      Pendidikan: 'S1 Pekerjaan Sosial',
      Pekerjaan: 'Pekerja Sosial',
      Alamat: 'Jl. Tulip No. 14, Desa C, Rundeng, Gayo Lues'
    },
    {
      Jenis_PSKS: 'D.USAHA',
      Kabupaten: 'Kota Banda Aceh',
      Kecamatan: 'Sultan Daulat',
      Gampong: 'Desa D',
      Nama_Lembaga: 'PT Sejahtera Bersama',
      Alamat: 'Jl. Industri No. 20, Desa D, Sultan Daulat, Kota Banda Aceh',
      Nama: 'Hendra Wijaya',
      NIK: '2345678901234568',
      JK: 'L',
      Tanggal_Lahir: '1970-11-12',
      Pendidikan: 'S2 Manajemen Bisnis',
      Pekerjaan: 'Direktur Utama'
    },
    {
      Jenis_PSKS: 'TKSK',
      Kabupaten: 'Kota Langsa',
      Kecamatan: 'Simpang Kiri',
      Gampong: 'Desa E',
      Nama: 'Rina Wulandari',
      NIK: '3456789012345679',
      JK: 'P',
      Tanggal_Lahir: '1986-08-03',
      Pendidikan: 'D3 Pekerjaan Sosial',
      Pekerjaan: 'Tenaga Kesejahteraan Sosial Kecamatan',
      Alamat: 'Jl. Nusa Indah No. 17, Desa E, Simpang Kiri, Kota Langsa'
    }
  ]
};